### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by sjung87** [waaman/Proxy-Wol-Redirect#1]
Hi waaman,
thanks for your great and simple Docker! I am new to the Docker thing and hope the question is not too stupid.

When redirecting to my Proxmox server, I am getting an SSLError. So the redirect does not work.
My Proxmox is local only, so I guess it does not get a certificate to validate. Even when putting the http-address as a redirect I am getting the same error (Proxmox itself is redirecting to https then). I attached the logs here as well.

What do I need to change in order to work in my situation?
Can there be a environment variable such as "ignore SSL"?

Thanks a lot! Best, Sebastian

[proxmox-wol-redirect.csv](https://github.com/waaman/Proxy-Wol-Redirect/files/12587237/proxmox-wol-redirect.csv)

**Comment by waaman** [comment]
Hello and thank you for your kind message.

For a quick test and perhaps solution can you try another docker image for a multiple redirect purpose:

```docker
docker run -d --name proxy-wol-redirect-multi -p 8888:80 waaman/proxy-wol-redirect-multi:latest
```

And visit http://localhost:8888

I will try to give some time searching solution for PWR specifically.

**Comment by sjung87** [comment]
Hi and thanks for the quick reply!

I found a solution for the issue. You can just add requests.get(domain, **verify=False**) and then only a warning will be thrown, but the redirect is working.
I would assume that a quite some people are facing this when redirecting to a local https with no valid certificate - probably it is worth to put it in / make it an environment variable if one wants to verify this or not.

Thanks and Best, Sebastian

**Comment by waaman** [comment]
Hi,

thank you for your tips . I can't test the fix but if you have time you can use the image
```
waaman/proxy-wol-redirect:test-ssl-verify
```

**Comment by sjung87** [comment]
Hi, sure - thanks for the quick update!

Just tested it (with various settings), but unfortunately it doesn't work.

I don't see why, the code seems to be correct. The only thing I added was the verify-part, so the code is similar.
The only thing I can imagine (not a python expert) is the type or something goes wrong when casting the type. I tested it with various inputs like "false", "False", … but didn't work. Maybe we can try not casting it at all.

**Comment by waaman** [comment]
Can you pull again
waaman/proxy-wol-redirect:test-ssl-verify

And set an environment variable: **SSL_VERIFY = "False"** on your target container run command ?

Thank you in advance,

**Comment by waaman** [comment]
I take more time and i tested myself.

I push a **latest** tagged image of **waaman/proxy-wol-redirect** with corrections added.
I guess you can now call it normallly and add an environment variable **SSL_VERIFY=False** if needed.

As you said warnings will be thrown.

A big thank you for your patience.

Let me know if something wrong, i let this issue open until all is ok about that.

Regards,

**Comment by sjung87** [comment]
Thanks a lot for your quick response and new version :)

I can confirm, now it is working as expected when setting the SSL_VERFIY to "False" in the latest image.

Thanks again for sharing this - it is very useful!
